### ISSUE TITLE
cfreq / cfsoq error

### ISSUE THREAD

**Issue by Plopptheblacke** [HyukIsBack/KARMA-DDoS#39]
when ever i try to attack something with cfreq or cfsoq i get this error 

[*] Bypassing CF... (Max 60s)
Traceback (most recent call last):
  File "browser.py", line 1173, in <module>
    if get_cookie(target):
  File "browser.py", line 70, in get_cookie
    driver = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.8/dist-packages/undetected_chromedriver/__init__.py", line 453, in __init__
    super(Chrome, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'executable_path'

**Comment by Plopptheblacke** [comment]
Also i changed to python3.9 instead of python3.8 it still wont work
