### ISSUE TITLE
tool not working after entering main.py command

### ISSUE THREAD

**Issue by MikeWIseX0** [HyukIsBack/KARMA-DDoS#43]
when i type `python3 main.py` it give me a traceback to the most recent call here is the error: 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/usr/local/lib/python3.11/dist-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/h/Downloads/KARMA-DDoS/main.py", line 3, in <module>
    import os, threading, requests, sys, cloudscraper, datetime, time, socket, socks, ssl, random, httpx
  File "/usr/lib/python3/dist-packages/cloudscraper/__init__.py", line 10, in <module>
    from requests_toolbelt.utils import dump
  File "/usr/lib/python3/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/usr/local/lib/python3.11/dist-packages/urllib3/contrib/__init__.py)

**Comment by 2077DevWave** [comment]
You probably did not install the required packages.  Or the packages are not installed in a separate environment.  The error is related to the import of required packages.
